node.id=1
process.roles=broker,controller
listeners=PLAINTEXT://localhost:9091,CONTROLLER://localhost:9093
advertised.listeners=PLAINTEXT://localhost:9091
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
controller.quorum.voters=1@localhost:9093
log.dirs=/var/lib/kafka/data

socket.send.buffer.bytes=1048576
socket.receive.buffer.bytes=1048576
socket.request.max.bytes=104857600

log.segment.bytes=1073741824
num.partitions=12
log.retention.hours=168
log.retention.bytes=-1
log.flush.interval.messages=50000
log.flush.interval.ms=10000

num.network.threads=8
num.io.threads=8
num.recovery.threads.per.data.dir=2

delete.topic.enable=true
auto.create.topics.enable=false
