upstream grpc_backend {
    server grpc-1:50051;
    server grpc-2:50051;
    server grpc-3:50051;
}

server {
    listen 50051;
    http2 on;

    location / {
        grpc_pass grpc://grpc_backend;
        grpc_buffer_size 16M;
        grpc_recv_timeout 300s;
        grpc_send_timeout 300s;
        grpc_read_timeout 300s;
        proxy_buffer_size 16M;
        proxy_buffers 8 16M;
    }
}
