upstream go_ws_backend {
    server go-ws-1:8092;
    server go-ws-2:8092;
    server go-ws-3:8092;
}

server {
    listen 50071;

    location / {
        proxy_pass http://go_ws_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_buffer_size 16M;
        proxy_buffers 8 16M;
    }
}
