services:
  uws-server:
    build: .
    ports:
      - "50061:8091"
    environment:
      KAFKA_BROKER: "192.168.0.9:9091"
      KAFKA_TOPIC: "benchmark-messages"
      PORT: "8091"
    deploy:
      replicas: 3
