upstream uws_backend {
    server uws-1:8091;
    server uws-2:8091;
    server uws-3:8091;
}

server {
    listen 50061;

    location / {
        proxy_pass http://uws_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_buffer_size 16M;
        proxy_buffers 8 16M;
    }
}
